In [1]:
import numpy as np
import pandas as pd
import random

In [2]:
# reading the data that is going to be used

recipes_df = pd.read_csv('allrecipes.csv', usecols = ["TITLES", "LINKS"])
recipes_df["recipeId"] = recipes_df.index+1
recipes_df = recipes_df[["recipeId", "TITLES", "LINKS"]]
recipes_df.head()

,recipeId,TITLES,LINKS
0,1,"""Kale""sadilla",https://www.simplyrecipes.com/recipes/kalesadi...
1,2,50/50 Martini,https://www.simplyrecipes.com/50-50-martini-51...
2,3,7 Layer Bean Dip,https://www.simplyrecipes.com/recipes/7_layer_...
3,4,Ahumado Hibisco Cocktail,https://www.simplyrecipes.com/recipes/ahumado_...
4,5,Air Fryer Avocado Fries,https://www.simplyrecipes.com/recipes/air_frye...

In [3]:
# creating fake dataset of ratings

userId = []
triedRecipeId = []
triedRecipeLiking = []
count = 0

for user in range(1,500):
    for numberOfTriedRecipes in range(random.randint(300, 400)):
        recipe = random.randint(1, len(recipes_df["recipeId"]))
        userId.append(user)
        triedRecipeId.append(recipe)
        triedRecipeLiking.append(random.randint(1, 5))
        count += numberOfTriedRecipes

ratings_df = pd.DataFrame(list(zip(userId, triedRecipeId, triedRecipeLiking)), columns =["userId", "recipeId", "rating"]) 
ratings_df = ratings_df.drop_duplicates(["userId", "recipeId"])
ratings_df

        userId  recipeId  rating
0            1       527       3
1            1       238       3
2            1       400       2
3            1        88       3
4            1       648       5
...        ...       ...     ...
173378     499       647       5
173379     499        36       1
173380     499       366       4
173381     499        35       1
173382     499       226       4

[142817 rows x 3 columns]

In [4]:
# saving the data

ratings_df.to_csv('ratings.csv', index = False)